# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.0
    - run: npm i -g yarn
    - run:  |
        git config --global user.email "action@github.com.au" && \
        git config --global user.name "Github Action" && \
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_KEY }}" >> ~/.npmrc
    - run: yarn --frozen-lockfile
    - run: yarn lerna publish patch --force-publish=* --yes
